version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    volumes:
      - ./staticfiles:/home/app/staticfiles/
      - ./data/db.sqlite3:/home/app/db.sqlite3
    ports:
      - "7000:7000"
    restart: always
    entrypoint: ["/entrypoint.sh"]
    command: gunicorn blog_project.wsgi:application --bind 0.0.0.0:7000

volumes:
  static_volume:
  db_volume: