version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    env_file:
      - .env
    volumes:
      - ./staticfiles:/home/app/staticfiles/
      - ./data/db.sqlite3:/home/app/db.sqlite3
    ports:
      - "8000:8000"
    restart: always
    entrypoint: ["/entrypoint.sh"]
    command: gunicorn blog_project.wsgi:application --bind 0.0.0.0:8000

volumes:
  static_volume:
  db_volume:


