# Generated by Django 5.2.4 on 2025-07-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_blog_date_last_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=60),
        ),
    ]
