# Each rout describes how an incoming URL will be processed by Platform.sh

"https://{default}/":
  type: upstream
  upstream: "the_code_chronicle:http"

"http://www.{default}/":
  type: redirect
  to: "https://{default}/"